namespace :countries do
  desc "TODO"
  task create_english_countries: :environment do
    Country.create(name: "Afghanistan", alpha2: "AF", alpha3: "AFG", numeric: "004")
    Country.create(name: "Aland Islands", alpha2: "AX", alpha3: "ALA", numeric: "248")
    Country.create(name: "Albania", alpha2: "AL", alpha3: "ALB", numeric: "008")
    Country.create(name: "Algeria", alpha2: "DZ", alpha3: "DZA", numeric: "012")
    Country.create(name: "American Samoa", alpha2: "AS", alpha3: "ASM", numeric: "016")
    Country.create(name: "Andorra", alpha2: "AD", alpha3: "AND", numeric: "020")
    Country.create(name: "Angola", alpha2: "AO", alpha3: "AGO", numeric: "024")
    Country.create(name: "Anguilla", alpha2: "AI", alpha3: "AIA", numeric: "660")
    Country.create(name: "Antarctica", alpha2: "AQ", alpha3: "ATA", numeric: "010")
    Country.create(name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", numeric: "028")
    Country.create(name: "Argentina", alpha2: "AR", alpha3: "ARG", numeric: "032")
    Country.create(name: "Armenia", alpha2: "AM", alpha3: "ARM", numeric: "051")
    Country.create(name: "Aruba", alpha2: "AW", alpha3: "ABW", numeric: "533")
    Country.create(name: "Australia", alpha2: "AU", alpha3: "AUS", numeric: "036")
    Country.create(name: "Austria", alpha2: "AT", alpha3: "AUT", numeric: "040")
    Country.create(name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", numeric: "031")
    Country.create(name: "Bahamas", alpha2: "BS", alpha3: "BHS", numeric: "044")
    Country.create(name: "Bahrain", alpha2: "BH", alpha3: "BHR", numeric: "048")
    Country.create(name: "Bangladesh", alpha2: "BD", alpha3: "BGD", numeric: "050")
    Country.create(name: "Barbados", alpha2: "BB", alpha3: "BRB", numeric: "052")
    Country.create(name: "Belarus", alpha2: "BY", alpha3: "BLR", numeric: "112")
    Country.create(name: "Belgium", alpha2: "BE", alpha3: "BEL", numeric: "056")
    Country.create(name: "Belize", alpha2: "BZ", alpha3: "BLZ", numeric: "084")
    Country.create(name: "Benin", alpha2: "BJ", alpha3: "BEN", numeric: "204")
    Country.create(name: "Bermuda", alpha2: "BM", alpha3: "BMU", numeric: "060")
    Country.create(name: "Bhutan", alpha2: "BT", alpha3: "BTN", numeric: "064")
    Country.create(name: "Bolivia", alpha2: "BO", alpha3: "BOL", numeric: "068")
    Country.create(name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", numeric: "070")
    Country.create(name: "Botswana", alpha2: "BW", alpha3: "BWA", numeric: "072")
    Country.create(name: "Bouvet Island", alpha2: "BV", alpha3: "BVT", numeric: "074")
    Country.create(name: "Brazil", alpha2: "BR", alpha3: "BRA", numeric: "076")
    Country.create(name: "British Virgin Islands", alpha2: "VG", alpha3: "VGB", numeric: "092")
    Country.create(name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", numeric: "086")
    Country.create(name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN", numeric: "096")
    Country.create(name: "Bulgaria", alpha2: "BG", alpha3: "BGR", numeric: "100")
    Country.create(name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", numeric: "854")
    Country.create(name: "Burundi", alpha2: "BI", alpha3: "BDI", numeric: "108")
    Country.create(name: "Cambodia", alpha2: "KH", alpha3: "KHM", numeric: "116")
    Country.create(name: "Cameroon", alpha2: "CM", alpha3: "CMR", numeric: "120")
    Country.create(name: "Canada", alpha2: "CA", alpha3: "CAN", numeric: "124")
    Country.create(name: "Cape Verde", alpha2: "CV", alpha3: "CPV", numeric: "132")
    Country.create(name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", numeric: "136")
    Country.create(name: "Central African Republic", alpha2: "CF", alpha3: "CAF", numeric: "140")
    Country.create(name: "Chad", alpha2: "TD", alpha3: "TCD", numeric: "148")
    Country.create(name: "Chile", alpha2: "CL", alpha3: "CHL", numeric: "152")
    Country.create(name: "China", alpha2: "CN", alpha3: "CHN", numeric: "156")
    Country.create(name: "Hong Kong, SAR China", alpha2: "HK", alpha3: "HKG", numeric: "344")
    Country.create(name: "Macao, SAR China", alpha2: "MO", alpha3: "MAC", numeric: "446")
    Country.create(name: "Christmas Island", alpha2: "CX", alpha3: "CXR", numeric: "162")
    Country.create(name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK", numeric: "166")
    Country.create(name: "Colombia", alpha2: "CO", alpha3: "COL", numeric: "170")
    Country.create(name: "Comoros", alpha2: "KM", alpha3: "COM", numeric: "174")
    Country.create(name: "Congo (Brazzaville)", alpha2: "CG", alpha3: "COG", numeric: "178")
    Country.create(name: "Congo, (Kinshasa)", alpha2: "CD", alpha3: "COD", numeric: "180")
    Country.create(name: "Cook Islands", alpha2: "CK", alpha3: "COK", numeric: "184")
    Country.create(name: "Costa Rica", alpha2: "CR", alpha3: "CRI", numeric: "188")
    Country.create(name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", numeric: "384")
    Country.create(name: "Croatia", alpha2: "HR", alpha3: "HRV", numeric: "191")
    Country.create(name: "Cuba", alpha2: "CU", alpha3: "CUB", numeric: "192")
    Country.create(name: "Cyprus", alpha2: "CY", alpha3: "CYP", numeric: "196")
    Country.create(name: "Czech Republic", alpha2: "CZ", alpha3: "CZE", numeric: "203")
    Country.create(name: "Denmark", alpha2: "DK", alpha3: "DNK", numeric: "208")
    Country.create(name: "Djibouti", alpha2: "DJ", alpha3: "DJI", numeric: "262")
    Country.create(name: "Dominica", alpha2: "DM", alpha3: "DMA", numeric: "212")
    Country.create(name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", numeric: "214")
    Country.create(name: "Ecuador", alpha2: "EC", alpha3: "ECU", numeric: "218")
    Country.create(name: "Egypt", alpha2: "EG", alpha3: "EGY", numeric: "818")
    Country.create(name: "El Salvador", alpha2: "SV", alpha3: "SLV", numeric: "222")
    Country.create(name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", numeric: "226")
    Country.create(name: "Eritrea", alpha2: "ER", alpha3: "ERI", numeric: "232")
    Country.create(name: "Estonia", alpha2: "EE", alpha3: "EST", numeric: "233")
    Country.create(name: "Ethiopia", alpha2: "ET", alpha3: "ETH", numeric: "231")
    Country.create(name: "Falkland Islands (Malvinas)", alpha2: "FK", alpha3: "FLK", numeric: "238")
    Country.create(name: "Faroe Islands", alpha2: "FO", alpha3: "FRO", numeric: "234")
    Country.create(name: "Fiji", alpha2: "FJ", alpha3: "FJI", numeric: "242")
    Country.create(name: "Finland", alpha2: "FI", alpha3: "FIN", numeric: "246")
    Country.create(name: "France", alpha2: "FR", alpha3: "FRA", numeric: "250")
    Country.create(name: "French Guiana", alpha2: "GF", alpha3: "GUF", numeric: "254")
    Country.create(name: "French Polynesia", alpha2: "PF", alpha3: "PYF", numeric: "258")
    Country.create(name: "French Southern Territories", alpha2: "TF", alpha3: "ATF", numeric: "260")
    Country.create(name: "Gabon", alpha2: "GA", alpha3: "GAB", numeric: "266")
    Country.create(name: "Gambia", alpha2: "GM", alpha3: "GMB", numeric: "270")
    Country.create(name: "Georgia", alpha2: "GE", alpha3: "GEO", numeric: "268")
    Country.create(name: "Germany", alpha2: "DE", alpha3: "DEU", numeric: "276")
    Country.create(name: "Ghana", alpha2: "GH", alpha3: "GHA", numeric: "288")
    Country.create(name: "Gibraltar", alpha2: "GI", alpha3: "GIB", numeric: "292")
    Country.create(name: "Greece", alpha2: "GR", alpha3: "GRC", numeric: "300")
    Country.create(name: "Greenland", alpha2: "GL", alpha3: "GRL", numeric: "304")
    Country.create(name: "Grenada", alpha2: "GD", alpha3: "GRD", numeric: "308")
    Country.create(name: "Guadeloupe", alpha2: "GP", alpha3: "GLP", numeric: "312")
    Country.create(name: "Guam", alpha2: "GU", alpha3: "GUM", numeric: "316")
    Country.create(name: "Guatemala", alpha2: "GT", alpha3: "GTM", numeric: "320")
    Country.create(name: "Guernsey", alpha2: "GG", alpha3: "GGY", numeric: "831")
    Country.create(name: "Guinea", alpha2: "GN", alpha3: "GIN", numeric: "324")
    Country.create(name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", numeric: "624")
    Country.create(name: "Guyana", alpha2: "GY", alpha3: "GUY", numeric: "328")
    Country.create(name: "Haiti", alpha2: "HT", alpha3: "HTI", numeric: "332")
    Country.create(name: "Heard and Mcdonald Islands", alpha2: "HM", alpha3: "HMD", numeric: "334")
    Country.create(name: "Holy See (Vatican City State)", alpha2: "VA", alpha3: "VAT", numeric: "336")
    Country.create(name: "Honduras", alpha2: "HN", alpha3: "HND", numeric: "340")
    Country.create(name: "Hungary", alpha2: "HU", alpha3: "HUN", numeric: "348")
    Country.create(name: "Iceland", alpha2: "IS", alpha3: "ISL", numeric: "352")
    Country.create(name: "India", alpha2: "IN", alpha3: "IND", numeric: "356")
    Country.create(name: "Indonesia", alpha2: "ID", alpha3: "IDN", numeric: "360")
    Country.create(name: "Iran, Islamic Republic of", alpha2: "IR", alpha3: "IRN", numeric: "364")
    Country.create(name: "Iraq", alpha2: "IQ", alpha3: "IRQ", numeric: "368")
    Country.create(name: "Ireland", alpha2: "IE", alpha3: "IRL", numeric: "372")
    Country.create(name: "Isle of Man", alpha2: "IM", alpha3: "IMN", numeric: "833")
    Country.create(name: "Israel", alpha2: "IL", alpha3: "ISR", numeric: "376")
    Country.create(name: "Italy", alpha2: "IT", alpha3: "ITA", numeric: "380")
    Country.create(name: "Jamaica", alpha2: "JM", alpha3: "JAM", numeric: "388")
    Country.create(name: "Japan", alpha2: "JP", alpha3: "JPN", numeric: "392")
    Country.create(name: "Jersey", alpha2: "JE", alpha3: "JEY", numeric: "832")
    Country.create(name: "Jordan", alpha2: "JO", alpha3: "JOR", numeric: "400")
    Country.create(name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", numeric: "398")
    Country.create(name: "Kenya", alpha2: "KE", alpha3: "KEN", numeric: "404")
    Country.create(name: "Kiribati", alpha2: "KI", alpha3: "KIR", numeric: "296")
    Country.create(name: "Korea (North)", alpha2: "KP", alpha3: "PRK", numeric: "408")
    Country.create(name: "Korea (South)", alpha2: "KR", alpha3: "KOR", numeric: "410")
    Country.create(name: "Kuwait", alpha2: "KW", alpha3: "KWT", numeric: "414")
    Country.create(name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", numeric: "417")
    Country.create(name: "Lao PDR", alpha2: "LA", alpha3: "LAO", numeric: "418")
    Country.create(name: "Latvia", alpha2: "LV", alpha3: "LVA", numeric: "428")
    Country.create(name: "Lebanon", alpha2: "LB", alpha3: "LBN", numeric: "422")
    Country.create(name: "Lesotho", alpha2: "LS", alpha3: "LSO", numeric: "426")
    Country.create(name: "Liberia", alpha2: "LR", alpha3: "LBR", numeric: "430")
    Country.create(name: "Libya", alpha2: "LY", alpha3: "LBY", numeric: "434")
    Country.create(name: "Liechtenstein", alpha2: "LI", alpha3: "LIE", numeric: "438")
    Country.create(name: "Lithuania", alpha2: "LT", alpha3: "LTU", numeric: "440")
    Country.create(name: "Luxembourg", alpha2: "LU", alpha3: "LUX", numeric: "442")
    Country.create(name: "Macedonia, Republic of", alpha2: "MK", alpha3: "MKD", numeric: "807")
    Country.create(name: "Madagascar", alpha2: "MG", alpha3: "MDG", numeric: "450")
    Country.create(name: "Malawi", alpha2: "MW", alpha3: "MWI", numeric: "454")
    Country.create(name: "Malaysia", alpha2: "MY", alpha3: "MYS", numeric: "458")
    Country.create(name: "Maldives", alpha2: "MV", alpha3: "MDV", numeric: "462")
    Country.create(name: "Mali", alpha2: "ML", alpha3: "MLI", numeric: "466")
    Country.create(name: "Malta", alpha2: "MT", alpha3: "MLT", numeric: "470")
    Country.create(name: "Marshall Islands", alpha2: "MH", alpha3: "MHL", numeric: "584")
    Country.create(name: "Martinique", alpha2: "MQ", alpha3: "MTQ", numeric: "474")
    Country.create(name: "Mauritania", alpha2: "MR", alpha3: "MRT", numeric: "478")
    Country.create(name: "Mauritius", alpha2: "MU", alpha3: "MUS", numeric: "480")
    Country.create(name: "Mayotte", alpha2: "YT", alpha3: "MYT", numeric: "175")
    Country.create(name: "Mexico", alpha2: "MX", alpha3: "MEX", numeric: "484")
    Country.create(name: "Micronesia, Federated States of", alpha2: "FM", alpha3: "FSM", numeric: "583")
    Country.create(name: "Moldova", alpha2: "MD", alpha3: "MDA", numeric: "498")
    Country.create(name: "Monaco", alpha2: "MC", alpha3: "MCO", numeric: "492")
    Country.create(name: "Mongolia", alpha2: "MN", alpha3: "MNG", numeric: "496")
    Country.create(name: "Montenegro", alpha2: "ME", alpha3: "MNE", numeric: "499")
    Country.create(name: "Montserrat", alpha2: "MS", alpha3: "MSR", numeric: "500")
    Country.create(name: "Morocco", alpha2: "MA", alpha3: "MAR", numeric: "504")
    Country.create(name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", numeric: "508")
    Country.create(name: "Myanmar", alpha2: "MM", alpha3: "MMR", numeric: "104")
    Country.create(name: "Namibia", alpha2: "NA", alpha3: "NAM", numeric: "516")
    Country.create(name: "Nauru", alpha2: "NR", alpha3: "NRU", numeric: "520")
    Country.create(name: "Nepal", alpha2: "NP", alpha3: "NPL", numeric: "524")
    Country.create(name: "Netherlands", alpha2: "NL", alpha3: "NLD", numeric: "528")
    Country.create(name: "Netherlands Antilles", alpha2: "AN", alpha3: "ANT", numeric: "530")
    Country.create(name: "New Caledonia", alpha2: "NC", alpha3: "NCL", numeric: "540")
    Country.create(name: "New Zealand", alpha2: "NZ", alpha3: "NZL", numeric: "554")
    Country.create(name: "Nicaragua", alpha2: "NI", alpha3: "NIC", numeric: "558")
    Country.create(name: "Niger", alpha2: "NE", alpha3: "NER", numeric: "562")
    Country.create(name: "Nigeria", alpha2: "NG", alpha3: "NGA", numeric: "566")
    Country.create(name: "Niue", alpha2: "NU", alpha3: "NIU", numeric: "570")
    Country.create(name: "Norfolk Island", alpha2: "NF", alpha3: "NFK", numeric: "574")
    Country.create(name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", numeric: "580")
    Country.create(name: "Norway", alpha2: "NO", alpha3: "NOR", numeric: "578")
    Country.create(name: "Oman", alpha2: "OM", alpha3: "OMN", numeric: "512")
    Country.create(name: "Pakistan", alpha2: "PK", alpha3: "PAK", numeric: "586")
    Country.create(name: "Palau", alpha2: "PW", alpha3: "PLW", numeric: "585")
    Country.create(name: "Palestinian Territory", alpha2: "PS", alpha3: "PSE", numeric: "275")
    Country.create(name: "Panama", alpha2: "PA", alpha3: "PAN", numeric: "591")
    Country.create(name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", numeric: "598")
    Country.create(name: "Paraguay", alpha2: "PY", alpha3: "PRY", numeric: "600")
    Country.create(name: "Peru", alpha2: "PE", alpha3: "PER", numeric: "604")
    Country.create(name: "Philippines", alpha2: "PH", alpha3: "PHL", numeric: "608")
    Country.create(name: "Pitcairn", alpha2: "PN", alpha3: "PCN", numeric: "612")
    Country.create(name: "Poland", alpha2: "PL", alpha3: "POL", numeric: "616")
    Country.create(name: "Portugal", alpha2: "PT", alpha3: "PRT", numeric: "620")
    Country.create(name: "Puerto Rico", alpha2: "PR", alpha3: "PRI", numeric: "630")
    Country.create(name: "Qatar", alpha2: "QA", alpha3: "QAT", numeric: "634")
    Country.create(name: "Réunion", alpha2: "RE", alpha3: "REU", numeric: "638")
    Country.create(name: "Romania", alpha2: "RO", alpha3: "ROU", numeric: "642")
    Country.create(name: "Russian Federation", alpha2: "RU", alpha3: "RUS", numeric: "643")
    Country.create(name: "Rwanda", alpha2: "RW", alpha3: "RWA", numeric: "646")
    Country.create(name: "Saint-Barthélemy", alpha2: "BL", alpha3: "BLM", numeric: "652")
    Country.create(name: "Saint Helena", alpha2: "SH", alpha3: "SHN", numeric: "654")
    Country.create(name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", numeric: "659")
    Country.create(name: "Saint Lucia", alpha2: "LC", alpha3: "LCA", numeric: "662")
    Country.create(name: "Saint-Martin (French part)", alpha2: "MF", alpha3: "MAF", numeric: "663")
    Country.create(name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM", numeric: "666")
    Country.create(name: "Saint Vincent and Grenadines", alpha2: "VC", alpha3: "VCT", numeric: "670")
    Country.create(name: "Samoa", alpha2: "WS", alpha3: "WSM", numeric: "882")
    Country.create(name: "San Marino", alpha2: "SM", alpha3: "SMR", numeric: "674")
    Country.create(name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", numeric: "678")
    Country.create(name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", numeric: "682")
    Country.create(name: "Senegal", alpha2: "SN", alpha3: "SEN", numeric: "686")
    Country.create(name: "Serbia", alpha2: "RS", alpha3: "SRB", numeric: "688")
    Country.create(name: "Seychelles", alpha2: "SC", alpha3: "SYC", numeric: "690")
    Country.create(name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", numeric: "694")
    Country.create(name: "Singapore", alpha2: "SG", alpha3: "SGP", numeric: "702")
    Country.create(name: "Slovakia", alpha2: "SK", alpha3: "SVK", numeric: "703")
    Country.create(name: "Slovenia", alpha2: "SI", alpha3: "SVN", numeric: "705")
    Country.create(name: "Solomon Islands", alpha2: "SB", alpha3: "SLB", numeric: "090")
    Country.create(name: "Somalia", alpha2: "SO", alpha3: "SOM", numeric: "706")
    Country.create(name: "South Africa", alpha2: "ZA", alpha3: "ZAF", numeric: "710")
    Country.create(name: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS", numeric: "239")
    Country.create(name: "South Sudan", alpha2: "SS", alpha3: "SSD", numeric: "728")
    Country.create(name: "Spain", alpha2: "ES", alpha3: "ESP", numeric: "724")
    Country.create(name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", numeric: "144")
    Country.create(name: "Sudan", alpha2: "SD", alpha3: "SDN", numeric: "736")
    Country.create(name: "Suriname", alpha2: "SR", alpha3: "SUR", numeric: "740")
    Country.create(name: "Svalbard and Jan Mayen Islands", alpha2: "SJ", alpha3: "SJM", numeric: "744")
    Country.create(name: "Swaziland", alpha2: "SZ", alpha3: "SWZ", numeric: "748")
    Country.create(name: "Sweden", alpha2: "SE", alpha3: "SWE", numeric: "752")
    Country.create(name: "Switzerland", alpha2: "CH", alpha3: "CHE", numeric: "756")
    Country.create(name: "Syrian Arab Republic (Syria)", alpha2: "SY", alpha3: "SYR", numeric: "760")
    Country.create(name: "Taiwan, Republic of China", alpha2: "TW", alpha3: "TWN", numeric: "158")
    Country.create(name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", numeric: "762")
    Country.create(name: "Tanzania, United Republic of", alpha2: "TZ", alpha3: "TZA", numeric: "834")
    Country.create(name: "Thailand", alpha2: "TH", alpha3: "THA", numeric: "764")
    Country.create(name: "Timor-Leste", alpha2: "TL", alpha3: "TLS", numeric: "626")
    Country.create(name: "Togo", alpha2: "TG", alpha3: "TGO", numeric: "768")
    Country.create(name: "Tokelau", alpha2: "TK", alpha3: "TKL", numeric: "772")
    Country.create(name: "Tonga", alpha2: "TO", alpha3: "TON", numeric: "776")
    Country.create(name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", numeric: "780")
    Country.create(name: "Tunisia", alpha2: "TN", alpha3: "TUN", numeric: "788")
    Country.create(name: "Turkey", alpha2: "TR", alpha3: "TUR", numeric: "792")
    Country.create(name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", numeric: "795")
    Country.create(name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", numeric: "796")
    Country.create(name: "Tuvalu", alpha2: "TV", alpha3: "TUV", numeric: "798")
    Country.create(name: "Uganda", alpha2: "UG", alpha3: "UGA", numeric: "800")
    Country.create(name: "Ukraine", alpha2: "UA", alpha3: "UKR", numeric: "804")
    Country.create(name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", numeric: "784")
    Country.create(name: "United Kingdom", alpha2: "GB", alpha3: "GBR", numeric: "826")
    Country.create(name: "United States of America", alpha2: "US", alpha3: "USA", numeric: "840")
    Country.create(name: "US Minor Outlying Islands", alpha2: "UM", alpha3: "UMI", numeric: "581")
    Country.create(name: "Uruguay", alpha2: "UY", alpha3: "URY", numeric: "858")
    Country.create(name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", numeric: "860")
    Country.create(name: "Vanuatu", alpha2: "VU", alpha3: "VUT", numeric: "548")
    Country.create(name: "Venezuela (Bolivarian Republic)", alpha2: "VE", alpha3: "VEN", numeric: "862")
    Country.create(name: "Viet Nam", alpha2: "VN", alpha3: "VNM", numeric: "704")
    Country.create(name: "Virgin Islands, US", alpha2: "VI", alpha3: "VIR", numeric: "850")
    Country.create(name: "Wallis and Futuna Islands", alpha2: "WF", alpha3: "WLF", numeric: "876")
    Country.create(name: "Western Sahara", alpha2: "EH", alpha3: "ESH", numeric: "732")
    Country.create(name: "Yemen", alpha2: "YE", alpha3: "YEM", numeric: "887")
    Country.create(name: "Zambia", alpha2: "ZM", alpha3: "ZMB", numeric: "894")
    Country.create(name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", numeric: "716")
  end

end
