# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: deee86adabffc3b2a7bdb05e2b3d1f4cd0e1de5b3364928ee6f490bf8d359d43d0b2ad76d3deb2cbdaa33bffec3df07587ca5dddaaad7a5a635cacc18209d7b5

test:
  secret_key_base: 0e3927fb35676d302fc3f197530d2baa2f0a4a211e64ff6a9fa0b61e23e25f5af9fa7bc1594f5f37929ebe8547b02b73be2ac00fe6239b9afb740a85f687ab28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
